### PR TITLE
[ECO-5702] Fix Xcode 26.4 compilation error

### LINKED ISSUE #2202: TypingOperationQueue.swift fails to compile on Xcode 26.4 / Swift 6.2 due to actor-isolation error
Building `ably-chat-swift` with Xcode 26.4 / Swift 6.2 fails in `Sources/AblyChat/TypingOperationQueue.swift` because of stricter actor-isolation/sendability
  checking.

  ### Compiler error

  ```text
  TypingOperationQueue.swift:96:38: error: sending 'pendingRequest' risks causing data races
  await pendingRequest.performOperation()
        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

  note: sending main actor-isolated 'pendingRequest' to nonisolated instance method 'performOperation()' risks causing data races between nonisolated and main
  actor-isolated uses
```

  ### Code

  TypingOperationQueue is @MainActor, and the failure happens in didFinishExecutingOperation() when a pending request is executed inside a Task:

```swift
@MainActor
internal class TypingOperationQueue<Failure: Error> {
  private struct Request {
    func performOperation() async {
      let result = await operation()
        complete(with: result)
    }

    func complete(with result: Result<Void, Failure>) {
      continuation.resume(returning: result)
    }
  }

  private func didFinishExecutingOperation() {
    if let pendingRequest {
      state = .executing(pendingRequest: nil)
        Task {
          await pendingRequest.performOperation()
            didFinishExecutingOperation()
        }
    } else {
      state = .idle
    }
  }
}
```

  ### What fixed it locally

  We were able to get the package compiling by explicitly marking the nested Request methods as @MainActor and making the task main-actor isolated as well:

```swift
@MainActor
func performOperation() async { ... }

@MainActor
func complete(with result: Result<Void, Failure>) { ... }

Task { @MainActor in
    await pendingRequest.performOperation()
    didFinishExecutingOperation()
}
```

  ### Environment

  - Xcode 26.4
  - Swift 6.2
  - iOS simulator build
  - Reproduced with ably-chat-swift 1.2.0

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5702) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
Resolves https://github.com/ably/ably-cocoa/issues/2202. See commit message for more details.

## Release Notes

* **Chores**
  * Updated CI/CD pipeline runner configuration to macOS 26 across all build jobs for improved compatibility and stability
  * Updated Xcode build tooling to version 26.4
  * Enhanced thread safety in asynchronous request handling

### CODE REVIEW

**Review by AndyTWF — APPROVED** [review]

**Review by ttypic — APPROVED** [review]
LGTM, just a thought: maybe it's worth to run on `macos-latest`? Can it help us find future bugs with new version of Xcode faster?

**Comment by lawrence-forooghian** [comment]
Unfortunately `macos-latest` isn't actually the latest; it's still on macOS 15! https://github.com/actions/runner-images?tab=readme-ov-file#available-images

and likewise the default version of xcode that the runners use is not the latest either; e.g. it's currently 26.2: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md

We _could_ have a CI job that also tests against whatever the default version of Xcode is too, so that we will _eventually_ catch issues introduced by new versions of Xcode (once they become the default)

**Comment by lawrence-forooghian** [comment]
I think another problem is the fact that we only run our CI jobs when we actually make a change, so in periods where there isn't much change on a given SDK it can take a while to find out; maybe we should consider nightly builds of everything too
