### ISSUE TITLE
Restore `.treatAllWarnings(as: .error)` in SPM package

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably-labs/ably-chat-swift#441]
Was introduced in a78e4ae and removed in #440 due to it causing a compilation error in users' apps.

Getting this issue in these Xcode versions:

- Version 26.0 (17A324)
- Version 26.1 beta 3 (17B5045g)

Have raised this with Apple, feedback ID FB20766714. Here's the repro project I attached: [ConflictingWarningsSettingsRepro.zip](https://github.com/user-attachments/files/23024797/ConflictingWarningsSettingsRepro.zip)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5617) by [Unito](https://www.unito.io)
